version: '3.5'

services:
  backend:
    container_name: backend
    restart: always
    image: backend:latest
    build: .
    command: python3 manage.py runserver 0:8000
    volumes:
      - .:/amika-backend
    ports:
      - "8000:8000"
    networks:
      - amika-net

networks: 
  amika-net:
    name: amika-net
    driver: bridge