version: '3.5'

services:
  db:
    container_name: db
    restart: always
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    networks:
      - amika-net
  
  backend:
    container_name: backend
    restart: always
    image: backend:latest
    build: .
    command: /bin/bash -l -c '
      python3 manage.py makemigrations &&
      python3 manage.py migrate --noinput &&
      python3 manage.py runserver 0:8000'
    volumes:
      - .:/amika-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - amika-net

networks: 
  amika-net:
    name: amika-net
    driver: bridge