version: '3.5'

services:
  db:
    container_name: db
    restart: always
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - amika-net

  backend:
    container_name: backend
    restart: always
    image: backend:latest
    build: .
    command: python3 manage.py runserver 0:8000
    volumes:
      - .:/amika-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
      - DEBUG=True
    depends_on:
      - db
    networks:
      - amika-net

networks: 
  amika-net:
    name: amika-net
    driver: bridge