# Generated by Django 2.2.5 on 2019-10-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amika', '0002_humor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=240, null=True)),
                ('data', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='materiais/')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amika.Aula')),
            ],
        ),
    ]
