# Generated by Django 2.2.5 on 2019-11-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amika', '0003_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tipo',
            field=models.CharField(choices=[['Individual', 'Individual'], ['Grupo', 'Grupo']], max_length=10),
        ),
    ]
