# Generated by Django 2.2.5 on 2019-11-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amika', '0005_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.FileField(null=True, upload_to='perfil/'),
        ),
    ]
