# Generated by Django 2.2.5 on 2019-11-06 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amika', '0005_formulario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['-data_encerramento', '-data_disponibilizacao', 'tipo', 'nome', 'descricao']},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='humor',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['arquivo__nome']},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['descricao']},
        ),
    ]
