# Generated by Django 2.2.5 on 2019-11-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amika', '0008_auto_20191108_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humor',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amika.Aluno'),
        ),
    ]
