# Generated by Django 2.2.5 on 2019-11-14 15:04

import amika.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amika', '0008_auto_20191108_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(null=True, upload_to=amika.models.aluno_foto_diretorio),
        ),
    ]
