# Generated by Django 2.2.5 on 2019-11-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amika', '0009_auto_20191114_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['arquivo']},
        ),
    ]
