# Generated by Django 2.2.5 on 2019-11-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amika', '0009_auto_20191109_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humor',
            name='aluno',
            field=models.IntegerField(),
        ),
    ]
