# Generated by Django 2.2.5 on 2019-11-15 21:21

import amika.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amika', '0009_auto_20191114_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaRealizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_ultima_alteracao', models.DateField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('anexo', models.FileField(null=True, upload_to=amika.models.aluno_agenda_realizada_diretorio)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amika.Agenda')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amika.Aluno')),
            ],
            options={
                'ordering': ['agenda__nome', '-data_ultima_alteracao', '-data_criacao', 'aluno__username'],
                'unique_together': {('agenda', 'aluno')},
            },
        ),
    ]
