# Generated by Django 2.2.5 on 2019-11-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amika', '0011_agendarealizada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendarealizada',
            options={'ordering': ['-agenda__data_encerramento', '-agenda__data_disponibilizacao', 'agenda__tipo', 'agenda__nome', '-data_ultima_alteracao', '-data_criacao', 'aluno__username']},
        ),
    ]
