# Generated by Django 2.2.5 on 2019-09-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=9)),
                ('turma', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAluno',
            fields=[
                ('matricula_aluno', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=70)),
                ('senha_aluno', models.CharField(max_length=400)),
                ('email_aluno', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
