# Generated by Django 2.2.5 on 2019-09-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UsuarioAluno',
        ),
        migrations.RenameField(
            model_name='usuarioaluno',
            old_name='email',
            new_name='email_aluno',
        ),
        migrations.RenameField(
            model_name='usuarioaluno',
            old_name='matricula',
            new_name='matricula_aluno',
        ),
        migrations.RenameField(
            model_name='usuarioaluno',
            old_name='nome',
            new_name='nome_aluno',
        ),
        migrations.RenameField(
            model_name='usuarioaluno',
            old_name='senha',
            new_name='senha_aluno',
        ),
    ]
