# Generated by Django 2.2.5 on 2019-09-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_usuario', '0002_auto_20190915_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=9)),
                ('turma', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarioaluno',
            name='email_aluno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarioaluno',
            name='nome_aluno',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='usuarioaluno',
            name='senha_aluno',
            field=models.CharField(max_length=400),
        ),
    ]
