# Generated by Django 2.2.5 on 2019-09-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_usuario', '0003_auto_20190916_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioaluno',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuarioaluno',
            name='email_aluno',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarioaluno',
            name='matricula_aluno',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
