# Generated by Django 2.2.5 on 2019-09-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('nome_turma', models.CharField(max_length=100)),
                ('ano_turma', models.IntegerField()),
                ('periodo_turma', models.IntegerField()),
                ('id_turma', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
