# Generated by Django 2.2.5 on 2019-10-16 03:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('Individual', 'Individual'), ('Grupo', 'Grupo')], max_length=10)),
                ('data_disponibilizacao', models.DateField(default=datetime.datetime.now)),
                ('data_encerramento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField()),
                ('texto', models.TextField(max_length=500)),
                ('arquivo', models.FileField(upload_to='')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda', to='turmas.Agenda')),
            ],
        ),
    ]
